# Generated by Django 5.1.1 on 2024-09-17 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='NaturalPerson',
        ),
        migrations.AddField(
            model_name='factor',
            name='natural_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.naturalperson'),
        ),
        migrations.AlterField(
            model_name='factor',
            name='legal_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.legalperson'),
        ),
    ]
