# Generated by Django 5.1.1 on 2024-09-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0002_remove_factor_naturalperson_factor_natural_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='legal_person',
        ),
    ]
