# Generated by Django 5.1.1 on 2024-09-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalperson',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
