# Generated by Django 5.1.1 on 2024-09-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='User',
            new_name='user',
        ),
    ]
